version: '3.8'
services:
  armada:
    image: 'armadak8s/armada'
    container_name: armada
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - build:/usr/src/app/build
volumes:
  node_modules:
  build:
